url: "https:///felos.live"

pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap