url: "https:///felos.live"
twitter: "https://twitter.com/felosnews"
facebook: "https://www.facebook.com/profile.php?id=100086191370479"
instagram: "https://instagram.com/felosnews"
twitch: "https://twitch.tv/felosnews"
youtube: "https://youtube.com/@felosnews"

pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap